# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/runner/work/unrar-browser-wasm/unrar-browser-wasm/packages/unrar-wasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/runner/work/unrar-browser-wasm/unrar-browser-wasm/packages/unrar-wasm/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/runner/work/unrar-browser-wasm/unrar-browser-wasm/packages/unrar-wasm/build/CMakeFiles /Users/runner/work/unrar-browser-wasm/unrar-browser-wasm/packages/unrar-wasm/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/runner/work/unrar-browser-wasm/unrar-browser-wasm/packages/unrar-wasm/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unrar

# Build rule for target.
unrar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unrar
.PHONY : unrar

# fast build rule for target.
unrar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/build
.PHONY : unrar/fast

src/unrar.o: src/unrar.cpp.o
.PHONY : src/unrar.o

# target to build an object file
src/unrar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/src/unrar.cpp.o
.PHONY : src/unrar.cpp.o

src/unrar.i: src/unrar.cpp.i
.PHONY : src/unrar.i

# target to preprocess a source file
src/unrar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/src/unrar.cpp.i
.PHONY : src/unrar.cpp.i

src/unrar.s: src/unrar.cpp.s
.PHONY : src/unrar.s

# target to generate assembly for a file
src/unrar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/src/unrar.cpp.s
.PHONY : src/unrar.cpp.s

vendor/unrar/archive.o: vendor/unrar/archive.cpp.o
.PHONY : vendor/unrar/archive.o

# target to build an object file
vendor/unrar/archive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/archive.cpp.o
.PHONY : vendor/unrar/archive.cpp.o

vendor/unrar/archive.i: vendor/unrar/archive.cpp.i
.PHONY : vendor/unrar/archive.i

# target to preprocess a source file
vendor/unrar/archive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/archive.cpp.i
.PHONY : vendor/unrar/archive.cpp.i

vendor/unrar/archive.s: vendor/unrar/archive.cpp.s
.PHONY : vendor/unrar/archive.s

# target to generate assembly for a file
vendor/unrar/archive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/archive.cpp.s
.PHONY : vendor/unrar/archive.cpp.s

vendor/unrar/arcread.o: vendor/unrar/arcread.cpp.o
.PHONY : vendor/unrar/arcread.o

# target to build an object file
vendor/unrar/arcread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/arcread.cpp.o
.PHONY : vendor/unrar/arcread.cpp.o

vendor/unrar/arcread.i: vendor/unrar/arcread.cpp.i
.PHONY : vendor/unrar/arcread.i

# target to preprocess a source file
vendor/unrar/arcread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/arcread.cpp.i
.PHONY : vendor/unrar/arcread.cpp.i

vendor/unrar/arcread.s: vendor/unrar/arcread.cpp.s
.PHONY : vendor/unrar/arcread.s

# target to generate assembly for a file
vendor/unrar/arcread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/arcread.cpp.s
.PHONY : vendor/unrar/arcread.cpp.s

vendor/unrar/blake2s.o: vendor/unrar/blake2s.cpp.o
.PHONY : vendor/unrar/blake2s.o

# target to build an object file
vendor/unrar/blake2s.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/blake2s.cpp.o
.PHONY : vendor/unrar/blake2s.cpp.o

vendor/unrar/blake2s.i: vendor/unrar/blake2s.cpp.i
.PHONY : vendor/unrar/blake2s.i

# target to preprocess a source file
vendor/unrar/blake2s.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/blake2s.cpp.i
.PHONY : vendor/unrar/blake2s.cpp.i

vendor/unrar/blake2s.s: vendor/unrar/blake2s.cpp.s
.PHONY : vendor/unrar/blake2s.s

# target to generate assembly for a file
vendor/unrar/blake2s.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/blake2s.cpp.s
.PHONY : vendor/unrar/blake2s.cpp.s

vendor/unrar/cmddata.o: vendor/unrar/cmddata.cpp.o
.PHONY : vendor/unrar/cmddata.o

# target to build an object file
vendor/unrar/cmddata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/cmddata.cpp.o
.PHONY : vendor/unrar/cmddata.cpp.o

vendor/unrar/cmddata.i: vendor/unrar/cmddata.cpp.i
.PHONY : vendor/unrar/cmddata.i

# target to preprocess a source file
vendor/unrar/cmddata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/cmddata.cpp.i
.PHONY : vendor/unrar/cmddata.cpp.i

vendor/unrar/cmddata.s: vendor/unrar/cmddata.cpp.s
.PHONY : vendor/unrar/cmddata.s

# target to generate assembly for a file
vendor/unrar/cmddata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/cmddata.cpp.s
.PHONY : vendor/unrar/cmddata.cpp.s

vendor/unrar/consio.o: vendor/unrar/consio.cpp.o
.PHONY : vendor/unrar/consio.o

# target to build an object file
vendor/unrar/consio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/consio.cpp.o
.PHONY : vendor/unrar/consio.cpp.o

vendor/unrar/consio.i: vendor/unrar/consio.cpp.i
.PHONY : vendor/unrar/consio.i

# target to preprocess a source file
vendor/unrar/consio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/consio.cpp.i
.PHONY : vendor/unrar/consio.cpp.i

vendor/unrar/consio.s: vendor/unrar/consio.cpp.s
.PHONY : vendor/unrar/consio.s

# target to generate assembly for a file
vendor/unrar/consio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/consio.cpp.s
.PHONY : vendor/unrar/consio.cpp.s

vendor/unrar/crc.o: vendor/unrar/crc.cpp.o
.PHONY : vendor/unrar/crc.o

# target to build an object file
vendor/unrar/crc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/crc.cpp.o
.PHONY : vendor/unrar/crc.cpp.o

vendor/unrar/crc.i: vendor/unrar/crc.cpp.i
.PHONY : vendor/unrar/crc.i

# target to preprocess a source file
vendor/unrar/crc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/crc.cpp.i
.PHONY : vendor/unrar/crc.cpp.i

vendor/unrar/crc.s: vendor/unrar/crc.cpp.s
.PHONY : vendor/unrar/crc.s

# target to generate assembly for a file
vendor/unrar/crc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/crc.cpp.s
.PHONY : vendor/unrar/crc.cpp.s

vendor/unrar/crypt.o: vendor/unrar/crypt.cpp.o
.PHONY : vendor/unrar/crypt.o

# target to build an object file
vendor/unrar/crypt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/crypt.cpp.o
.PHONY : vendor/unrar/crypt.cpp.o

vendor/unrar/crypt.i: vendor/unrar/crypt.cpp.i
.PHONY : vendor/unrar/crypt.i

# target to preprocess a source file
vendor/unrar/crypt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/crypt.cpp.i
.PHONY : vendor/unrar/crypt.cpp.i

vendor/unrar/crypt.s: vendor/unrar/crypt.cpp.s
.PHONY : vendor/unrar/crypt.s

# target to generate assembly for a file
vendor/unrar/crypt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/crypt.cpp.s
.PHONY : vendor/unrar/crypt.cpp.s

vendor/unrar/dll.o: vendor/unrar/dll.cpp.o
.PHONY : vendor/unrar/dll.o

# target to build an object file
vendor/unrar/dll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/dll.cpp.o
.PHONY : vendor/unrar/dll.cpp.o

vendor/unrar/dll.i: vendor/unrar/dll.cpp.i
.PHONY : vendor/unrar/dll.i

# target to preprocess a source file
vendor/unrar/dll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/dll.cpp.i
.PHONY : vendor/unrar/dll.cpp.i

vendor/unrar/dll.s: vendor/unrar/dll.cpp.s
.PHONY : vendor/unrar/dll.s

# target to generate assembly for a file
vendor/unrar/dll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/dll.cpp.s
.PHONY : vendor/unrar/dll.cpp.s

vendor/unrar/encname.o: vendor/unrar/encname.cpp.o
.PHONY : vendor/unrar/encname.o

# target to build an object file
vendor/unrar/encname.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/encname.cpp.o
.PHONY : vendor/unrar/encname.cpp.o

vendor/unrar/encname.i: vendor/unrar/encname.cpp.i
.PHONY : vendor/unrar/encname.i

# target to preprocess a source file
vendor/unrar/encname.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/encname.cpp.i
.PHONY : vendor/unrar/encname.cpp.i

vendor/unrar/encname.s: vendor/unrar/encname.cpp.s
.PHONY : vendor/unrar/encname.s

# target to generate assembly for a file
vendor/unrar/encname.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/encname.cpp.s
.PHONY : vendor/unrar/encname.cpp.s

vendor/unrar/errhnd.o: vendor/unrar/errhnd.cpp.o
.PHONY : vendor/unrar/errhnd.o

# target to build an object file
vendor/unrar/errhnd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/errhnd.cpp.o
.PHONY : vendor/unrar/errhnd.cpp.o

vendor/unrar/errhnd.i: vendor/unrar/errhnd.cpp.i
.PHONY : vendor/unrar/errhnd.i

# target to preprocess a source file
vendor/unrar/errhnd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/errhnd.cpp.i
.PHONY : vendor/unrar/errhnd.cpp.i

vendor/unrar/errhnd.s: vendor/unrar/errhnd.cpp.s
.PHONY : vendor/unrar/errhnd.s

# target to generate assembly for a file
vendor/unrar/errhnd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/errhnd.cpp.s
.PHONY : vendor/unrar/errhnd.cpp.s

vendor/unrar/extinfo.o: vendor/unrar/extinfo.cpp.o
.PHONY : vendor/unrar/extinfo.o

# target to build an object file
vendor/unrar/extinfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/extinfo.cpp.o
.PHONY : vendor/unrar/extinfo.cpp.o

vendor/unrar/extinfo.i: vendor/unrar/extinfo.cpp.i
.PHONY : vendor/unrar/extinfo.i

# target to preprocess a source file
vendor/unrar/extinfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/extinfo.cpp.i
.PHONY : vendor/unrar/extinfo.cpp.i

vendor/unrar/extinfo.s: vendor/unrar/extinfo.cpp.s
.PHONY : vendor/unrar/extinfo.s

# target to generate assembly for a file
vendor/unrar/extinfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/extinfo.cpp.s
.PHONY : vendor/unrar/extinfo.cpp.s

vendor/unrar/extract.o: vendor/unrar/extract.cpp.o
.PHONY : vendor/unrar/extract.o

# target to build an object file
vendor/unrar/extract.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/extract.cpp.o
.PHONY : vendor/unrar/extract.cpp.o

vendor/unrar/extract.i: vendor/unrar/extract.cpp.i
.PHONY : vendor/unrar/extract.i

# target to preprocess a source file
vendor/unrar/extract.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/extract.cpp.i
.PHONY : vendor/unrar/extract.cpp.i

vendor/unrar/extract.s: vendor/unrar/extract.cpp.s
.PHONY : vendor/unrar/extract.s

# target to generate assembly for a file
vendor/unrar/extract.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/extract.cpp.s
.PHONY : vendor/unrar/extract.cpp.s

vendor/unrar/filcreat.o: vendor/unrar/filcreat.cpp.o
.PHONY : vendor/unrar/filcreat.o

# target to build an object file
vendor/unrar/filcreat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filcreat.cpp.o
.PHONY : vendor/unrar/filcreat.cpp.o

vendor/unrar/filcreat.i: vendor/unrar/filcreat.cpp.i
.PHONY : vendor/unrar/filcreat.i

# target to preprocess a source file
vendor/unrar/filcreat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filcreat.cpp.i
.PHONY : vendor/unrar/filcreat.cpp.i

vendor/unrar/filcreat.s: vendor/unrar/filcreat.cpp.s
.PHONY : vendor/unrar/filcreat.s

# target to generate assembly for a file
vendor/unrar/filcreat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filcreat.cpp.s
.PHONY : vendor/unrar/filcreat.cpp.s

vendor/unrar/file.o: vendor/unrar/file.cpp.o
.PHONY : vendor/unrar/file.o

# target to build an object file
vendor/unrar/file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/file.cpp.o
.PHONY : vendor/unrar/file.cpp.o

vendor/unrar/file.i: vendor/unrar/file.cpp.i
.PHONY : vendor/unrar/file.i

# target to preprocess a source file
vendor/unrar/file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/file.cpp.i
.PHONY : vendor/unrar/file.cpp.i

vendor/unrar/file.s: vendor/unrar/file.cpp.s
.PHONY : vendor/unrar/file.s

# target to generate assembly for a file
vendor/unrar/file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/file.cpp.s
.PHONY : vendor/unrar/file.cpp.s

vendor/unrar/filefn.o: vendor/unrar/filefn.cpp.o
.PHONY : vendor/unrar/filefn.o

# target to build an object file
vendor/unrar/filefn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filefn.cpp.o
.PHONY : vendor/unrar/filefn.cpp.o

vendor/unrar/filefn.i: vendor/unrar/filefn.cpp.i
.PHONY : vendor/unrar/filefn.i

# target to preprocess a source file
vendor/unrar/filefn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filefn.cpp.i
.PHONY : vendor/unrar/filefn.cpp.i

vendor/unrar/filefn.s: vendor/unrar/filefn.cpp.s
.PHONY : vendor/unrar/filefn.s

# target to generate assembly for a file
vendor/unrar/filefn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filefn.cpp.s
.PHONY : vendor/unrar/filefn.cpp.s

vendor/unrar/filestr.o: vendor/unrar/filestr.cpp.o
.PHONY : vendor/unrar/filestr.o

# target to build an object file
vendor/unrar/filestr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filestr.cpp.o
.PHONY : vendor/unrar/filestr.cpp.o

vendor/unrar/filestr.i: vendor/unrar/filestr.cpp.i
.PHONY : vendor/unrar/filestr.i

# target to preprocess a source file
vendor/unrar/filestr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filestr.cpp.i
.PHONY : vendor/unrar/filestr.cpp.i

vendor/unrar/filestr.s: vendor/unrar/filestr.cpp.s
.PHONY : vendor/unrar/filestr.s

# target to generate assembly for a file
vendor/unrar/filestr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/filestr.cpp.s
.PHONY : vendor/unrar/filestr.cpp.s

vendor/unrar/find.o: vendor/unrar/find.cpp.o
.PHONY : vendor/unrar/find.o

# target to build an object file
vendor/unrar/find.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/find.cpp.o
.PHONY : vendor/unrar/find.cpp.o

vendor/unrar/find.i: vendor/unrar/find.cpp.i
.PHONY : vendor/unrar/find.i

# target to preprocess a source file
vendor/unrar/find.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/find.cpp.i
.PHONY : vendor/unrar/find.cpp.i

vendor/unrar/find.s: vendor/unrar/find.cpp.s
.PHONY : vendor/unrar/find.s

# target to generate assembly for a file
vendor/unrar/find.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/find.cpp.s
.PHONY : vendor/unrar/find.cpp.s

vendor/unrar/getbits.o: vendor/unrar/getbits.cpp.o
.PHONY : vendor/unrar/getbits.o

# target to build an object file
vendor/unrar/getbits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/getbits.cpp.o
.PHONY : vendor/unrar/getbits.cpp.o

vendor/unrar/getbits.i: vendor/unrar/getbits.cpp.i
.PHONY : vendor/unrar/getbits.i

# target to preprocess a source file
vendor/unrar/getbits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/getbits.cpp.i
.PHONY : vendor/unrar/getbits.cpp.i

vendor/unrar/getbits.s: vendor/unrar/getbits.cpp.s
.PHONY : vendor/unrar/getbits.s

# target to generate assembly for a file
vendor/unrar/getbits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/getbits.cpp.s
.PHONY : vendor/unrar/getbits.cpp.s

vendor/unrar/global.o: vendor/unrar/global.cpp.o
.PHONY : vendor/unrar/global.o

# target to build an object file
vendor/unrar/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/global.cpp.o
.PHONY : vendor/unrar/global.cpp.o

vendor/unrar/global.i: vendor/unrar/global.cpp.i
.PHONY : vendor/unrar/global.i

# target to preprocess a source file
vendor/unrar/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/global.cpp.i
.PHONY : vendor/unrar/global.cpp.i

vendor/unrar/global.s: vendor/unrar/global.cpp.s
.PHONY : vendor/unrar/global.s

# target to generate assembly for a file
vendor/unrar/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/global.cpp.s
.PHONY : vendor/unrar/global.cpp.s

vendor/unrar/hash.o: vendor/unrar/hash.cpp.o
.PHONY : vendor/unrar/hash.o

# target to build an object file
vendor/unrar/hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/hash.cpp.o
.PHONY : vendor/unrar/hash.cpp.o

vendor/unrar/hash.i: vendor/unrar/hash.cpp.i
.PHONY : vendor/unrar/hash.i

# target to preprocess a source file
vendor/unrar/hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/hash.cpp.i
.PHONY : vendor/unrar/hash.cpp.i

vendor/unrar/hash.s: vendor/unrar/hash.cpp.s
.PHONY : vendor/unrar/hash.s

# target to generate assembly for a file
vendor/unrar/hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/hash.cpp.s
.PHONY : vendor/unrar/hash.cpp.s

vendor/unrar/headers.o: vendor/unrar/headers.cpp.o
.PHONY : vendor/unrar/headers.o

# target to build an object file
vendor/unrar/headers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/headers.cpp.o
.PHONY : vendor/unrar/headers.cpp.o

vendor/unrar/headers.i: vendor/unrar/headers.cpp.i
.PHONY : vendor/unrar/headers.i

# target to preprocess a source file
vendor/unrar/headers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/headers.cpp.i
.PHONY : vendor/unrar/headers.cpp.i

vendor/unrar/headers.s: vendor/unrar/headers.cpp.s
.PHONY : vendor/unrar/headers.s

# target to generate assembly for a file
vendor/unrar/headers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/headers.cpp.s
.PHONY : vendor/unrar/headers.cpp.s

vendor/unrar/largepage.o: vendor/unrar/largepage.cpp.o
.PHONY : vendor/unrar/largepage.o

# target to build an object file
vendor/unrar/largepage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/largepage.cpp.o
.PHONY : vendor/unrar/largepage.cpp.o

vendor/unrar/largepage.i: vendor/unrar/largepage.cpp.i
.PHONY : vendor/unrar/largepage.i

# target to preprocess a source file
vendor/unrar/largepage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/largepage.cpp.i
.PHONY : vendor/unrar/largepage.cpp.i

vendor/unrar/largepage.s: vendor/unrar/largepage.cpp.s
.PHONY : vendor/unrar/largepage.s

# target to generate assembly for a file
vendor/unrar/largepage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/largepage.cpp.s
.PHONY : vendor/unrar/largepage.cpp.s

vendor/unrar/list.o: vendor/unrar/list.cpp.o
.PHONY : vendor/unrar/list.o

# target to build an object file
vendor/unrar/list.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/list.cpp.o
.PHONY : vendor/unrar/list.cpp.o

vendor/unrar/list.i: vendor/unrar/list.cpp.i
.PHONY : vendor/unrar/list.i

# target to preprocess a source file
vendor/unrar/list.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/list.cpp.i
.PHONY : vendor/unrar/list.cpp.i

vendor/unrar/list.s: vendor/unrar/list.cpp.s
.PHONY : vendor/unrar/list.s

# target to generate assembly for a file
vendor/unrar/list.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/list.cpp.s
.PHONY : vendor/unrar/list.cpp.s

vendor/unrar/match.o: vendor/unrar/match.cpp.o
.PHONY : vendor/unrar/match.o

# target to build an object file
vendor/unrar/match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/match.cpp.o
.PHONY : vendor/unrar/match.cpp.o

vendor/unrar/match.i: vendor/unrar/match.cpp.i
.PHONY : vendor/unrar/match.i

# target to preprocess a source file
vendor/unrar/match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/match.cpp.i
.PHONY : vendor/unrar/match.cpp.i

vendor/unrar/match.s: vendor/unrar/match.cpp.s
.PHONY : vendor/unrar/match.s

# target to generate assembly for a file
vendor/unrar/match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/match.cpp.s
.PHONY : vendor/unrar/match.cpp.s

vendor/unrar/options.o: vendor/unrar/options.cpp.o
.PHONY : vendor/unrar/options.o

# target to build an object file
vendor/unrar/options.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/options.cpp.o
.PHONY : vendor/unrar/options.cpp.o

vendor/unrar/options.i: vendor/unrar/options.cpp.i
.PHONY : vendor/unrar/options.i

# target to preprocess a source file
vendor/unrar/options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/options.cpp.i
.PHONY : vendor/unrar/options.cpp.i

vendor/unrar/options.s: vendor/unrar/options.cpp.s
.PHONY : vendor/unrar/options.s

# target to generate assembly for a file
vendor/unrar/options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/options.cpp.s
.PHONY : vendor/unrar/options.cpp.s

vendor/unrar/pathfn.o: vendor/unrar/pathfn.cpp.o
.PHONY : vendor/unrar/pathfn.o

# target to build an object file
vendor/unrar/pathfn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/pathfn.cpp.o
.PHONY : vendor/unrar/pathfn.cpp.o

vendor/unrar/pathfn.i: vendor/unrar/pathfn.cpp.i
.PHONY : vendor/unrar/pathfn.i

# target to preprocess a source file
vendor/unrar/pathfn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/pathfn.cpp.i
.PHONY : vendor/unrar/pathfn.cpp.i

vendor/unrar/pathfn.s: vendor/unrar/pathfn.cpp.s
.PHONY : vendor/unrar/pathfn.s

# target to generate assembly for a file
vendor/unrar/pathfn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/pathfn.cpp.s
.PHONY : vendor/unrar/pathfn.cpp.s

vendor/unrar/qopen.o: vendor/unrar/qopen.cpp.o
.PHONY : vendor/unrar/qopen.o

# target to build an object file
vendor/unrar/qopen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/qopen.cpp.o
.PHONY : vendor/unrar/qopen.cpp.o

vendor/unrar/qopen.i: vendor/unrar/qopen.cpp.i
.PHONY : vendor/unrar/qopen.i

# target to preprocess a source file
vendor/unrar/qopen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/qopen.cpp.i
.PHONY : vendor/unrar/qopen.cpp.i

vendor/unrar/qopen.s: vendor/unrar/qopen.cpp.s
.PHONY : vendor/unrar/qopen.s

# target to generate assembly for a file
vendor/unrar/qopen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/qopen.cpp.s
.PHONY : vendor/unrar/qopen.cpp.s

vendor/unrar/rar.o: vendor/unrar/rar.cpp.o
.PHONY : vendor/unrar/rar.o

# target to build an object file
vendor/unrar/rar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rar.cpp.o
.PHONY : vendor/unrar/rar.cpp.o

vendor/unrar/rar.i: vendor/unrar/rar.cpp.i
.PHONY : vendor/unrar/rar.i

# target to preprocess a source file
vendor/unrar/rar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rar.cpp.i
.PHONY : vendor/unrar/rar.cpp.i

vendor/unrar/rar.s: vendor/unrar/rar.cpp.s
.PHONY : vendor/unrar/rar.s

# target to generate assembly for a file
vendor/unrar/rar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rar.cpp.s
.PHONY : vendor/unrar/rar.cpp.s

vendor/unrar/rarvm.o: vendor/unrar/rarvm.cpp.o
.PHONY : vendor/unrar/rarvm.o

# target to build an object file
vendor/unrar/rarvm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rarvm.cpp.o
.PHONY : vendor/unrar/rarvm.cpp.o

vendor/unrar/rarvm.i: vendor/unrar/rarvm.cpp.i
.PHONY : vendor/unrar/rarvm.i

# target to preprocess a source file
vendor/unrar/rarvm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rarvm.cpp.i
.PHONY : vendor/unrar/rarvm.cpp.i

vendor/unrar/rarvm.s: vendor/unrar/rarvm.cpp.s
.PHONY : vendor/unrar/rarvm.s

# target to generate assembly for a file
vendor/unrar/rarvm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rarvm.cpp.s
.PHONY : vendor/unrar/rarvm.cpp.s

vendor/unrar/rawread.o: vendor/unrar/rawread.cpp.o
.PHONY : vendor/unrar/rawread.o

# target to build an object file
vendor/unrar/rawread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rawread.cpp.o
.PHONY : vendor/unrar/rawread.cpp.o

vendor/unrar/rawread.i: vendor/unrar/rawread.cpp.i
.PHONY : vendor/unrar/rawread.i

# target to preprocess a source file
vendor/unrar/rawread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rawread.cpp.i
.PHONY : vendor/unrar/rawread.cpp.i

vendor/unrar/rawread.s: vendor/unrar/rawread.cpp.s
.PHONY : vendor/unrar/rawread.s

# target to generate assembly for a file
vendor/unrar/rawread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rawread.cpp.s
.PHONY : vendor/unrar/rawread.cpp.s

vendor/unrar/rdwrfn.o: vendor/unrar/rdwrfn.cpp.o
.PHONY : vendor/unrar/rdwrfn.o

# target to build an object file
vendor/unrar/rdwrfn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rdwrfn.cpp.o
.PHONY : vendor/unrar/rdwrfn.cpp.o

vendor/unrar/rdwrfn.i: vendor/unrar/rdwrfn.cpp.i
.PHONY : vendor/unrar/rdwrfn.i

# target to preprocess a source file
vendor/unrar/rdwrfn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rdwrfn.cpp.i
.PHONY : vendor/unrar/rdwrfn.cpp.i

vendor/unrar/rdwrfn.s: vendor/unrar/rdwrfn.cpp.s
.PHONY : vendor/unrar/rdwrfn.s

# target to generate assembly for a file
vendor/unrar/rdwrfn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/rdwrfn.cpp.s
.PHONY : vendor/unrar/rdwrfn.cpp.s

vendor/unrar/resource.o: vendor/unrar/resource.cpp.o
.PHONY : vendor/unrar/resource.o

# target to build an object file
vendor/unrar/resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/resource.cpp.o
.PHONY : vendor/unrar/resource.cpp.o

vendor/unrar/resource.i: vendor/unrar/resource.cpp.i
.PHONY : vendor/unrar/resource.i

# target to preprocess a source file
vendor/unrar/resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/resource.cpp.i
.PHONY : vendor/unrar/resource.cpp.i

vendor/unrar/resource.s: vendor/unrar/resource.cpp.s
.PHONY : vendor/unrar/resource.s

# target to generate assembly for a file
vendor/unrar/resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/resource.cpp.s
.PHONY : vendor/unrar/resource.cpp.s

vendor/unrar/secpassword.o: vendor/unrar/secpassword.cpp.o
.PHONY : vendor/unrar/secpassword.o

# target to build an object file
vendor/unrar/secpassword.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/secpassword.cpp.o
.PHONY : vendor/unrar/secpassword.cpp.o

vendor/unrar/secpassword.i: vendor/unrar/secpassword.cpp.i
.PHONY : vendor/unrar/secpassword.i

# target to preprocess a source file
vendor/unrar/secpassword.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/secpassword.cpp.i
.PHONY : vendor/unrar/secpassword.cpp.i

vendor/unrar/secpassword.s: vendor/unrar/secpassword.cpp.s
.PHONY : vendor/unrar/secpassword.s

# target to generate assembly for a file
vendor/unrar/secpassword.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/secpassword.cpp.s
.PHONY : vendor/unrar/secpassword.cpp.s

vendor/unrar/sha1.o: vendor/unrar/sha1.cpp.o
.PHONY : vendor/unrar/sha1.o

# target to build an object file
vendor/unrar/sha1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/sha1.cpp.o
.PHONY : vendor/unrar/sha1.cpp.o

vendor/unrar/sha1.i: vendor/unrar/sha1.cpp.i
.PHONY : vendor/unrar/sha1.i

# target to preprocess a source file
vendor/unrar/sha1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/sha1.cpp.i
.PHONY : vendor/unrar/sha1.cpp.i

vendor/unrar/sha1.s: vendor/unrar/sha1.cpp.s
.PHONY : vendor/unrar/sha1.s

# target to generate assembly for a file
vendor/unrar/sha1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/sha1.cpp.s
.PHONY : vendor/unrar/sha1.cpp.s

vendor/unrar/sha256.o: vendor/unrar/sha256.cpp.o
.PHONY : vendor/unrar/sha256.o

# target to build an object file
vendor/unrar/sha256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/sha256.cpp.o
.PHONY : vendor/unrar/sha256.cpp.o

vendor/unrar/sha256.i: vendor/unrar/sha256.cpp.i
.PHONY : vendor/unrar/sha256.i

# target to preprocess a source file
vendor/unrar/sha256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/sha256.cpp.i
.PHONY : vendor/unrar/sha256.cpp.i

vendor/unrar/sha256.s: vendor/unrar/sha256.cpp.s
.PHONY : vendor/unrar/sha256.s

# target to generate assembly for a file
vendor/unrar/sha256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/sha256.cpp.s
.PHONY : vendor/unrar/sha256.cpp.s

vendor/unrar/smallfn.o: vendor/unrar/smallfn.cpp.o
.PHONY : vendor/unrar/smallfn.o

# target to build an object file
vendor/unrar/smallfn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/smallfn.cpp.o
.PHONY : vendor/unrar/smallfn.cpp.o

vendor/unrar/smallfn.i: vendor/unrar/smallfn.cpp.i
.PHONY : vendor/unrar/smallfn.i

# target to preprocess a source file
vendor/unrar/smallfn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/smallfn.cpp.i
.PHONY : vendor/unrar/smallfn.cpp.i

vendor/unrar/smallfn.s: vendor/unrar/smallfn.cpp.s
.PHONY : vendor/unrar/smallfn.s

# target to generate assembly for a file
vendor/unrar/smallfn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/smallfn.cpp.s
.PHONY : vendor/unrar/smallfn.cpp.s

vendor/unrar/strfn.o: vendor/unrar/strfn.cpp.o
.PHONY : vendor/unrar/strfn.o

# target to build an object file
vendor/unrar/strfn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/strfn.cpp.o
.PHONY : vendor/unrar/strfn.cpp.o

vendor/unrar/strfn.i: vendor/unrar/strfn.cpp.i
.PHONY : vendor/unrar/strfn.i

# target to preprocess a source file
vendor/unrar/strfn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/strfn.cpp.i
.PHONY : vendor/unrar/strfn.cpp.i

vendor/unrar/strfn.s: vendor/unrar/strfn.cpp.s
.PHONY : vendor/unrar/strfn.s

# target to generate assembly for a file
vendor/unrar/strfn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/strfn.cpp.s
.PHONY : vendor/unrar/strfn.cpp.s

vendor/unrar/strlist.o: vendor/unrar/strlist.cpp.o
.PHONY : vendor/unrar/strlist.o

# target to build an object file
vendor/unrar/strlist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/strlist.cpp.o
.PHONY : vendor/unrar/strlist.cpp.o

vendor/unrar/strlist.i: vendor/unrar/strlist.cpp.i
.PHONY : vendor/unrar/strlist.i

# target to preprocess a source file
vendor/unrar/strlist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/strlist.cpp.i
.PHONY : vendor/unrar/strlist.cpp.i

vendor/unrar/strlist.s: vendor/unrar/strlist.cpp.s
.PHONY : vendor/unrar/strlist.s

# target to generate assembly for a file
vendor/unrar/strlist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/strlist.cpp.s
.PHONY : vendor/unrar/strlist.cpp.s

vendor/unrar/system.o: vendor/unrar/system.cpp.o
.PHONY : vendor/unrar/system.o

# target to build an object file
vendor/unrar/system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/system.cpp.o
.PHONY : vendor/unrar/system.cpp.o

vendor/unrar/system.i: vendor/unrar/system.cpp.i
.PHONY : vendor/unrar/system.i

# target to preprocess a source file
vendor/unrar/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/system.cpp.i
.PHONY : vendor/unrar/system.cpp.i

vendor/unrar/system.s: vendor/unrar/system.cpp.s
.PHONY : vendor/unrar/system.s

# target to generate assembly for a file
vendor/unrar/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/system.cpp.s
.PHONY : vendor/unrar/system.cpp.s

vendor/unrar/threadpool.o: vendor/unrar/threadpool.cpp.o
.PHONY : vendor/unrar/threadpool.o

# target to build an object file
vendor/unrar/threadpool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/threadpool.cpp.o
.PHONY : vendor/unrar/threadpool.cpp.o

vendor/unrar/threadpool.i: vendor/unrar/threadpool.cpp.i
.PHONY : vendor/unrar/threadpool.i

# target to preprocess a source file
vendor/unrar/threadpool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/threadpool.cpp.i
.PHONY : vendor/unrar/threadpool.cpp.i

vendor/unrar/threadpool.s: vendor/unrar/threadpool.cpp.s
.PHONY : vendor/unrar/threadpool.s

# target to generate assembly for a file
vendor/unrar/threadpool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/threadpool.cpp.s
.PHONY : vendor/unrar/threadpool.cpp.s

vendor/unrar/timefn.o: vendor/unrar/timefn.cpp.o
.PHONY : vendor/unrar/timefn.o

# target to build an object file
vendor/unrar/timefn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/timefn.cpp.o
.PHONY : vendor/unrar/timefn.cpp.o

vendor/unrar/timefn.i: vendor/unrar/timefn.cpp.i
.PHONY : vendor/unrar/timefn.i

# target to preprocess a source file
vendor/unrar/timefn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/timefn.cpp.i
.PHONY : vendor/unrar/timefn.cpp.i

vendor/unrar/timefn.s: vendor/unrar/timefn.cpp.s
.PHONY : vendor/unrar/timefn.s

# target to generate assembly for a file
vendor/unrar/timefn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/timefn.cpp.s
.PHONY : vendor/unrar/timefn.cpp.s

vendor/unrar/ui.o: vendor/unrar/ui.cpp.o
.PHONY : vendor/unrar/ui.o

# target to build an object file
vendor/unrar/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/ui.cpp.o
.PHONY : vendor/unrar/ui.cpp.o

vendor/unrar/ui.i: vendor/unrar/ui.cpp.i
.PHONY : vendor/unrar/ui.i

# target to preprocess a source file
vendor/unrar/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/ui.cpp.i
.PHONY : vendor/unrar/ui.cpp.i

vendor/unrar/ui.s: vendor/unrar/ui.cpp.s
.PHONY : vendor/unrar/ui.s

# target to generate assembly for a file
vendor/unrar/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/ui.cpp.s
.PHONY : vendor/unrar/ui.cpp.s

vendor/unrar/unicode.o: vendor/unrar/unicode.cpp.o
.PHONY : vendor/unrar/unicode.o

# target to build an object file
vendor/unrar/unicode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/unicode.cpp.o
.PHONY : vendor/unrar/unicode.cpp.o

vendor/unrar/unicode.i: vendor/unrar/unicode.cpp.i
.PHONY : vendor/unrar/unicode.i

# target to preprocess a source file
vendor/unrar/unicode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/unicode.cpp.i
.PHONY : vendor/unrar/unicode.cpp.i

vendor/unrar/unicode.s: vendor/unrar/unicode.cpp.s
.PHONY : vendor/unrar/unicode.s

# target to generate assembly for a file
vendor/unrar/unicode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/unicode.cpp.s
.PHONY : vendor/unrar/unicode.cpp.s

vendor/unrar/unpack.o: vendor/unrar/unpack.cpp.o
.PHONY : vendor/unrar/unpack.o

# target to build an object file
vendor/unrar/unpack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/unpack.cpp.o
.PHONY : vendor/unrar/unpack.cpp.o

vendor/unrar/unpack.i: vendor/unrar/unpack.cpp.i
.PHONY : vendor/unrar/unpack.i

# target to preprocess a source file
vendor/unrar/unpack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/unpack.cpp.i
.PHONY : vendor/unrar/unpack.cpp.i

vendor/unrar/unpack.s: vendor/unrar/unpack.cpp.s
.PHONY : vendor/unrar/unpack.s

# target to generate assembly for a file
vendor/unrar/unpack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/unpack.cpp.s
.PHONY : vendor/unrar/unpack.cpp.s

vendor/unrar/volume.o: vendor/unrar/volume.cpp.o
.PHONY : vendor/unrar/volume.o

# target to build an object file
vendor/unrar/volume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/volume.cpp.o
.PHONY : vendor/unrar/volume.cpp.o

vendor/unrar/volume.i: vendor/unrar/volume.cpp.i
.PHONY : vendor/unrar/volume.i

# target to preprocess a source file
vendor/unrar/volume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/volume.cpp.i
.PHONY : vendor/unrar/volume.cpp.i

vendor/unrar/volume.s: vendor/unrar/volume.cpp.s
.PHONY : vendor/unrar/volume.s

# target to generate assembly for a file
vendor/unrar/volume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unrar.dir/build.make CMakeFiles/unrar.dir/vendor/unrar/volume.cpp.s
.PHONY : vendor/unrar/volume.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... unrar"
	@echo "... src/unrar.o"
	@echo "... src/unrar.i"
	@echo "... src/unrar.s"
	@echo "... vendor/unrar/archive.o"
	@echo "... vendor/unrar/archive.i"
	@echo "... vendor/unrar/archive.s"
	@echo "... vendor/unrar/arcread.o"
	@echo "... vendor/unrar/arcread.i"
	@echo "... vendor/unrar/arcread.s"
	@echo "... vendor/unrar/blake2s.o"
	@echo "... vendor/unrar/blake2s.i"
	@echo "... vendor/unrar/blake2s.s"
	@echo "... vendor/unrar/cmddata.o"
	@echo "... vendor/unrar/cmddata.i"
	@echo "... vendor/unrar/cmddata.s"
	@echo "... vendor/unrar/consio.o"
	@echo "... vendor/unrar/consio.i"
	@echo "... vendor/unrar/consio.s"
	@echo "... vendor/unrar/crc.o"
	@echo "... vendor/unrar/crc.i"
	@echo "... vendor/unrar/crc.s"
	@echo "... vendor/unrar/crypt.o"
	@echo "... vendor/unrar/crypt.i"
	@echo "... vendor/unrar/crypt.s"
	@echo "... vendor/unrar/dll.o"
	@echo "... vendor/unrar/dll.i"
	@echo "... vendor/unrar/dll.s"
	@echo "... vendor/unrar/encname.o"
	@echo "... vendor/unrar/encname.i"
	@echo "... vendor/unrar/encname.s"
	@echo "... vendor/unrar/errhnd.o"
	@echo "... vendor/unrar/errhnd.i"
	@echo "... vendor/unrar/errhnd.s"
	@echo "... vendor/unrar/extinfo.o"
	@echo "... vendor/unrar/extinfo.i"
	@echo "... vendor/unrar/extinfo.s"
	@echo "... vendor/unrar/extract.o"
	@echo "... vendor/unrar/extract.i"
	@echo "... vendor/unrar/extract.s"
	@echo "... vendor/unrar/filcreat.o"
	@echo "... vendor/unrar/filcreat.i"
	@echo "... vendor/unrar/filcreat.s"
	@echo "... vendor/unrar/file.o"
	@echo "... vendor/unrar/file.i"
	@echo "... vendor/unrar/file.s"
	@echo "... vendor/unrar/filefn.o"
	@echo "... vendor/unrar/filefn.i"
	@echo "... vendor/unrar/filefn.s"
	@echo "... vendor/unrar/filestr.o"
	@echo "... vendor/unrar/filestr.i"
	@echo "... vendor/unrar/filestr.s"
	@echo "... vendor/unrar/find.o"
	@echo "... vendor/unrar/find.i"
	@echo "... vendor/unrar/find.s"
	@echo "... vendor/unrar/getbits.o"
	@echo "... vendor/unrar/getbits.i"
	@echo "... vendor/unrar/getbits.s"
	@echo "... vendor/unrar/global.o"
	@echo "... vendor/unrar/global.i"
	@echo "... vendor/unrar/global.s"
	@echo "... vendor/unrar/hash.o"
	@echo "... vendor/unrar/hash.i"
	@echo "... vendor/unrar/hash.s"
	@echo "... vendor/unrar/headers.o"
	@echo "... vendor/unrar/headers.i"
	@echo "... vendor/unrar/headers.s"
	@echo "... vendor/unrar/largepage.o"
	@echo "... vendor/unrar/largepage.i"
	@echo "... vendor/unrar/largepage.s"
	@echo "... vendor/unrar/list.o"
	@echo "... vendor/unrar/list.i"
	@echo "... vendor/unrar/list.s"
	@echo "... vendor/unrar/match.o"
	@echo "... vendor/unrar/match.i"
	@echo "... vendor/unrar/match.s"
	@echo "... vendor/unrar/options.o"
	@echo "... vendor/unrar/options.i"
	@echo "... vendor/unrar/options.s"
	@echo "... vendor/unrar/pathfn.o"
	@echo "... vendor/unrar/pathfn.i"
	@echo "... vendor/unrar/pathfn.s"
	@echo "... vendor/unrar/qopen.o"
	@echo "... vendor/unrar/qopen.i"
	@echo "... vendor/unrar/qopen.s"
	@echo "... vendor/unrar/rar.o"
	@echo "... vendor/unrar/rar.i"
	@echo "... vendor/unrar/rar.s"
	@echo "... vendor/unrar/rarvm.o"
	@echo "... vendor/unrar/rarvm.i"
	@echo "... vendor/unrar/rarvm.s"
	@echo "... vendor/unrar/rawread.o"
	@echo "... vendor/unrar/rawread.i"
	@echo "... vendor/unrar/rawread.s"
	@echo "... vendor/unrar/rdwrfn.o"
	@echo "... vendor/unrar/rdwrfn.i"
	@echo "... vendor/unrar/rdwrfn.s"
	@echo "... vendor/unrar/resource.o"
	@echo "... vendor/unrar/resource.i"
	@echo "... vendor/unrar/resource.s"
	@echo "... vendor/unrar/secpassword.o"
	@echo "... vendor/unrar/secpassword.i"
	@echo "... vendor/unrar/secpassword.s"
	@echo "... vendor/unrar/sha1.o"
	@echo "... vendor/unrar/sha1.i"
	@echo "... vendor/unrar/sha1.s"
	@echo "... vendor/unrar/sha256.o"
	@echo "... vendor/unrar/sha256.i"
	@echo "... vendor/unrar/sha256.s"
	@echo "... vendor/unrar/smallfn.o"
	@echo "... vendor/unrar/smallfn.i"
	@echo "... vendor/unrar/smallfn.s"
	@echo "... vendor/unrar/strfn.o"
	@echo "... vendor/unrar/strfn.i"
	@echo "... vendor/unrar/strfn.s"
	@echo "... vendor/unrar/strlist.o"
	@echo "... vendor/unrar/strlist.i"
	@echo "... vendor/unrar/strlist.s"
	@echo "... vendor/unrar/system.o"
	@echo "... vendor/unrar/system.i"
	@echo "... vendor/unrar/system.s"
	@echo "... vendor/unrar/threadpool.o"
	@echo "... vendor/unrar/threadpool.i"
	@echo "... vendor/unrar/threadpool.s"
	@echo "... vendor/unrar/timefn.o"
	@echo "... vendor/unrar/timefn.i"
	@echo "... vendor/unrar/timefn.s"
	@echo "... vendor/unrar/ui.o"
	@echo "... vendor/unrar/ui.i"
	@echo "... vendor/unrar/ui.s"
	@echo "... vendor/unrar/unicode.o"
	@echo "... vendor/unrar/unicode.i"
	@echo "... vendor/unrar/unicode.s"
	@echo "... vendor/unrar/unpack.o"
	@echo "... vendor/unrar/unpack.i"
	@echo "... vendor/unrar/unpack.s"
	@echo "... vendor/unrar/volume.o"
	@echo "... vendor/unrar/volume.i"
	@echo "... vendor/unrar/volume.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

